# Generated by Django 5.0.6 on 2024-05-27 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки')),
                ('finish_time', models.DateTimeField(verbose_name='Конец рассылки')),
                ('frequency', models.CharField(choices=[('d', 'ежедневно'), ('w', 'еженедельно'), ('m', 'ежемесячно')], default='d', max_length=1, verbose_name='Периодичность')),
                ('status', models.CharField(blank=True, choices=[('c', 'создана'), ('s', 'запущена'), ('f', 'завершена')], default=None, max_length=1, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronym', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('mailing_id', models.ManyToManyField(related_name='clients', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_attempt', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('mailing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['latest_attempt'],
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Тело письма')),
                ('mailing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение рассылки',
                'verbose_name_plural': 'Сообщения рассылкок',
            },
        ),
    ]
