# Generated by Django 5.0.6 on 2024-05-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
