# Generated by Django 5.0.6 on 2024-05-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingattempt_mailing_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_id',
        ),
        migrations.RemoveField(
            model_name='mailingmessage',
            name='mailing_id',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(related_name='clients', to='mailing.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailing', to='mailing.mailingmessage', verbose_name='Сообщение'),
        ),
    ]
