# Generated by Django 5.0.6 on 2024-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailingmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
