# Generated by Django 5.0.6 on 2024-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_alter_mailing_options_alter_mailingmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'создана'), ('s', 'запущена'), ('f', 'завершена')], default='c', max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
