# Generated by Django 5.0.6 on 2024-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('c', 'создана'), ('s', 'запущена'), ('f', 'завершена')], default='c', max_length=1, verbose_name='Статус'),
        ),
    ]
