# Generated by Django 5.0.6 on 2024-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_time',
            field=models.DateField(verbose_name='Конец рассылки'),
        ),
    ]
