# Generated by Django 5.0.6 on 2024-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_alter_mailing_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_time',
            field=models.DateField(verbose_name='Последний день'),
        ),
    ]
