# Generated by Django 5.0.6 on 2024-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='latest_attempt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Последняя попытка'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Результат'),
        ),
    ]
