# Generated by Django 5.0.6 on 2024-06-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_alter_mailingattempt_latest_attempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['-latest_attempt'], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
    ]
