# Generated by Django 5.0.6 on 2024-06-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0021_alter_mailingattempt_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-start_time'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
