# Generated by Django 5.0.6 on 2024-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0023_client_user_mailing_user_mailingmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
