# Generated by Django 5.0.6 on 2024-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0024_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-start_time'], 'permissions': [('can_stop_mailing', 'can stop mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='stopped_by_manager',
            field=models.BooleanField(default=False, verbose_name='Отключена менеджером'),
        ),
    ]
