# Generated by Django 5.0.6 on 2024-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0025_alter_mailing_options_mailing_stopped_by_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='stopped_by_manager',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('c', 'создана'), ('s', 'запущена'), ('f', 'завершена'), ('t', 'остановлена'), ('p', 'приостановлена')], default='c', max_length=1, verbose_name='Статус'),
        ),
    ]
